# Generated by Django 2.1.3 on 2019-01-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employees.models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_company', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=employees.models.upload_file_path)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_acc', models.CharField(max_length=150)),
                ('designation', models.CharField(choices=[('human-resource', 'human-resource'), ('operations-Man', 'operations-Man'), ('assit-account', 'assit-account'), ('assit-human-r', 'assit-human-r'), ('admin-assist', 'admin-assist'), ('manager-it', 'manager-it'), ('accountant', 'accountant'), ('programmer', 'programmer'), ('marketer', 'marketer'), ('admin', 'admin')], max_length=120)),
                ('staff_type', models.CharField(choices=[('contract', 'contract'), ('part-time', 'part-time'), ('full-time', 'full-time'), ('industrials', 'industrials'), ('internship', 'internship')], max_length=120)),
                ('appraisals', models.PositiveIntegerField(default=0)),
                ('displinary', models.PositiveIntegerField(default=0)),
                ('staff_key', models.CharField(default='x5506f474', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfileTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to=employees.models.upload_path)),
                ('files', models.FileField(blank=True, null=True, upload_to=employees.models.upload_file_path)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_acc', models.CharField(max_length=150)),
                ('designation', models.CharField(choices=[('human-resource', 'human-resource'), ('operations-Man', 'operations-Man'), ('assit-account', 'assit-account'), ('assit-human-r', 'assit-human-r'), ('admin-assist', 'admin-assist'), ('manager-it', 'manager-it'), ('accountant', 'accountant'), ('programmer', 'programmer'), ('marketer', 'marketer'), ('admin', 'admin')], max_length=120)),
                ('staff_type', models.CharField(choices=[('contract', 'contract'), ('part-time', 'part-time'), ('full-time', 'full-time'), ('industrials', 'industrials'), ('internship', 'internship')], max_length=120)),
                ('appraisals', models.PositiveIntegerField(default=0)),
                ('displinary', models.PositiveIntegerField(default=0)),
                ('pending', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(upload_to=employees.models.upload_path)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('years_known', models.CharField(max_length=200)),
                ('phone', models.CharField(help_text='phone1, phone2,,,', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('files', models.TextField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_acc', models.CharField(max_length=150)),
                ('designation', models.CharField(choices=[('human-resource', 'human-resource'), ('operations-Man', 'operations-Man'), ('assit-account', 'assit-account'), ('assit-human-r', 'assit-human-r'), ('admin-assist', 'admin-assist'), ('manager-it', 'manager-it'), ('accountant', 'accountant'), ('programmer', 'programmer'), ('marketer', 'marketer'), ('admin', 'admin')], max_length=120)),
                ('staff_type', models.CharField(choices=[('contract', 'contract'), ('part-time', 'part-time'), ('full-time', 'full-time'), ('industrials', 'industrials'), ('internship', 'internship')], max_length=120)),
                ('appraisals', models.PositiveIntegerField(default=0)),
                ('displinary', models.PositiveIntegerField(default=0)),
                ('staff_key', models.CharField(default='x5506f474', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.Department')),
                ('employee_temp_profil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.EmployeeProfileTemp')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical employee profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeProfileTemp',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('avatar', models.TextField(blank=True, default='default.png', max_length=100, null=True)),
                ('files', models.TextField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_acc', models.CharField(max_length=150)),
                ('designation', models.CharField(choices=[('human-resource', 'human-resource'), ('operations-Man', 'operations-Man'), ('assit-account', 'assit-account'), ('assit-human-r', 'assit-human-r'), ('admin-assist', 'admin-assist'), ('manager-it', 'manager-it'), ('accountant', 'accountant'), ('programmer', 'programmer'), ('marketer', 'marketer'), ('admin', 'admin')], max_length=120)),
                ('staff_type', models.CharField(choices=[('contract', 'contract'), ('part-time', 'part-time'), ('full-time', 'full-time'), ('industrials', 'industrials'), ('internship', 'internship')], max_length=120)),
                ('appraisals', models.PositiveIntegerField(default=0)),
                ('displinary', models.PositiveIntegerField(default=0)),
                ('pending', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.Department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.EmployeeProfile')),
            ],
            options={
                'verbose_name': 'historical employee profile temp',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
