# Generated by Django 2.1.3 on 2019-01-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffwelfare', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofiletemp',
            name='training',
            field=models.ManyToManyField(blank=True, to='staffwelfare.Training'),
        ),
        migrations.AddField(
            model_name='employeeprofiletemp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_temp_profile', to='employees.EmployeeProfile'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Department'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_temp_profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeProfileTemp'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='training',
            field=models.ManyToManyField(blank=True, to='staffwelfare.Training'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
