# Generated by Django 2.1.3 on 2019-01-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20190129_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='xf85373ef', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='xf85373ef', max_length=100),
        ),
    ]
