# Generated by Django 2.1.3 on 2019-02-01 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20190129_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='default.png', null=True, upload_to=employees.models.upload_path)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='employeeprofiletemp',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='historicalemployeeprofiletemp',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='xbe88f4b4', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='xbe88f4b4', max_length=100),
        ),
    ]
