# Generated by Django 2.1.3 on 2019-02-03 17:31

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190202_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='x48469753', max_length=100),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=employees.models.upload_path),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='x48469753', max_length=100),
        ),
    ]
