# Generated by Django 2.1.3 on 2019-02-03 18:27

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20190203_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='xb599e50', max_length=100),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='image',
            field=models.ImageField(default='default.png', upload_to=employees.models.upload_path),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='xb599e50', max_length=100),
        ),
    ]
