# Generated by Django 2.1.3 on 2019-02-03 18:29

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20190203_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='x63fbe661', max_length=100),
        ),
        migrations.AlterField(
            model_name='guarantor',
            name='image',
            field=models.ImageField(upload_to=employees.models.upload_path),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='x63fbe661', max_length=100),
        ),
    ]
