# Generated by Django 2.1.3 on 2019-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20190204_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='x75edb28c', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='x75edb28c', max_length=100),
        ),
    ]
