# Generated by Django 2.1.3 on 2019-02-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20190224_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='x9f5e8d88', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='x9f5e8d88', max_length=100),
        ),
    ]
