# Generated by Django 2.1.3 on 2019-03-02 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_auto_20190228_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_temp_profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeProfileTemp'),
        ),
        migrations.AddField(
            model_name='historicalemployeeprofile',
            name='employee_temp_profil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.EmployeeProfileTemp'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='staff_key',
            field=models.CharField(default='xa782cbba', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalemployeeprofile',
            name='staff_key',
            field=models.CharField(default='xa782cbba', max_length=100),
        ),
    ]
