# Generated by Django 2.1.3 on 2019-01-29 20:40

import company.models
from django.db import migrations, models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_url', models.UUIDField(default=uuid.UUID('58c4f97a-ae65-4d7d-91d3-3f12e5a23a2b'), editable=False)),
                ('full_name', models.CharField(help_text="Company's Name..", max_length=255)),
                ('shortname', models.CharField(blank=True, help_text="Company's Short-name..", max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('vision', models.CharField(help_text="Company's Vision..", max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=company.models.upload_file_path)),
                ('mission', models.CharField(default="Company's Mission.", max_length=255)),
                ('country', models.CharField(default='Federal Republic Of Nigeria.', max_length=200)),
                ('state', models.CharField(choices=[('FCT Abuja', 'FCT Abuja'), ('Lagos Nigeria', 'Lagos Nigeria'), ('Nasarawa', 'Nasarawa'), ('Kogi', 'Kogi')], max_length=120)),
                ('city', models.CharField(choices=[('FCT Abuja', 'FCT Abuja'), ('Lekki', 'Lekki'), ('Badagri', 'Badagri'), ('Lokoja', 'Lokoja'), ('Lafia', 'Lafia'), ('Keffi', 'Keffi'), ('Karu', 'Karu'), ('Okene', 'Okene')], max_length=120)),
                ('employees', models.PositiveIntegerField(default=1)),
                ('cac_code', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCompanyProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('company_url', models.UUIDField(default=uuid.UUID('58c4f97a-ae65-4d7d-91d3-3f12e5a23a2b'), editable=False)),
                ('full_name', models.CharField(help_text="Company's Name..", max_length=255)),
                ('shortname', models.CharField(blank=True, help_text="Company's Short-name..", max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('vision', models.CharField(help_text="Company's Vision..", max_length=255)),
                ('file', models.TextField(blank=True, max_length=100, null=True)),
                ('mission', models.CharField(default="Company's Mission.", max_length=255)),
                ('country', models.CharField(default='Federal Republic Of Nigeria.', max_length=200)),
                ('state', models.CharField(choices=[('FCT Abuja', 'FCT Abuja'), ('Lagos Nigeria', 'Lagos Nigeria'), ('Nasarawa', 'Nasarawa'), ('Kogi', 'Kogi')], max_length=120)),
                ('city', models.CharField(choices=[('FCT Abuja', 'FCT Abuja'), ('Lekki', 'Lekki'), ('Badagri', 'Badagri'), ('Lokoja', 'Lokoja'), ('Lafia', 'Lafia'), ('Keffi', 'Keffi'), ('Karu', 'Karu'), ('Okene', 'Okene')], max_length=120)),
                ('employees', models.PositiveIntegerField(default=1)),
                ('cac_code', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical company profile',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
