# Generated by Django 2.1.3 on 2019-01-29 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190129_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('0c5ddb7a-d876-4898-bba1-0b1f14719921'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('0c5ddb7a-d876-4898-bba1-0b1f14719921'), editable=False),
        ),
    ]
