# Generated by Django 2.1.3 on 2019-01-29 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190129_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('fef3fe34-af0c-4cb3-b146-a88d024d7d70'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('fef3fe34-af0c-4cb3-b146-a88d024d7d70'), editable=False),
        ),
    ]
