# Generated by Django 2.1.3 on 2019-02-01 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190129_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('6ec24228-7b74-4223-b6ad-d1f9d06d462b'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('6ec24228-7b74-4223-b6ad-d1f9d06d462b'), editable=False),
        ),
    ]
