# Generated by Django 2.1.3 on 2019-02-02 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190201_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('d20203cf-3a0a-49d0-8727-3d270b7c51c1'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('d20203cf-3a0a-49d0-8727-3d270b7c51c1'), editable=False),
        ),
    ]
