# Generated by Django 2.1.3 on 2019-02-02 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190202_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('0e5911bf-7b98-4a44-9b74-b4a7829262af'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('0e5911bf-7b98-4a44-9b74-b4a7829262af'), editable=False),
        ),
    ]
