# Generated by Django 2.1.3 on 2019-02-03 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20190202_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('e32af0dc-cd22-4396-bda9-4b85ec962b0a'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('e32af0dc-cd22-4396-bda9-4b85ec962b0a'), editable=False),
        ),
    ]
