# Generated by Django 2.1.3 on 2019-02-04 20:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20190204_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('def0a7e9-7385-409d-9fed-903273114a34'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('def0a7e9-7385-409d-9fed-903273114a34'), editable=False),
        ),
    ]
