# Generated by Django 2.1.3 on 2019-02-24 22:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20190204_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('9985ac8d-9a9d-4edc-9892-10d9965d5de7'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('9985ac8d-9a9d-4edc-9892-10d9965d5de7'), editable=False),
        ),
    ]
