# Generated by Django 2.1.3 on 2019-02-24 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20190224_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('d73ff7aa-7458-41c3-ae43-e5d13369e6f9'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('d73ff7aa-7458-41c3-ae43-e5d13369e6f9'), editable=False),
        ),
    ]
