# Generated by Django 2.1.3 on 2019-02-25 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20190224_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('99c82708-d092-4cbe-89de-4f049d754ee4'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('99c82708-d092-4cbe-89de-4f049d754ee4'), editable=False),
        ),
    ]
