# Generated by Django 2.1.3 on 2019-02-25 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20190225_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('56b85b91-d50c-46b2-b972-f1625523e6c0'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('56b85b91-d50c-46b2-b972-f1625523e6c0'), editable=False),
        ),
    ]
