# Generated by Django 2.1.3 on 2019-02-28 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20190225_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('f19cb72f-5d1a-4e50-a56e-ddddbc209254'), editable=False),
        ),
        migrations.AlterField(
            model_name='historicalcompanyprofile',
            name='company_url',
            field=models.UUIDField(default=uuid.UUID('f19cb72f-5d1a-4e50-a56e-ddddbc209254'), editable=False),
        ),
    ]
