# Generated by Django 2.1.3 on 2019-02-24 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0013_auto_20190224_2214'),
        ('staffwelfare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('human-resource', 'human-resource'), ('operations-Man', 'operations-Man'), ('assit-account', 'assit-account'), ('assit-human-r', 'assit-human-r'), ('admin-assist', 'admin-assist'), ('manager-it', 'manager-it'), ('accountant', 'accountant'), ('programmer', 'programmer'), ('marketer', 'marketer'), ('admin', 'admin')], max_length=120)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=100000000)),
                ('tax_apply', models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True)),
                ('wardrobe_allowee', models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True)),
                ('health_allowee', models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True)),
                ('transport_allowee', models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('withheld', 'Withheld')], default='pending', max_length=100)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Department')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tax_rate_apply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffwelfare.Tax')),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pension_rate', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
    ]
