# Generated by Django 2.1.3 on 2019-02-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffwelfare', '0002_payment_pension'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalary',
            name='pension_apply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='pension_rate_apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staffwelfare.Pension'),
        ),
    ]
