# Generated by Django 2.1.3 on 2019-02-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwelfare', '0003_auto_20190224_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tax_rate_apply',
        ),
        migrations.AddField(
            model_name='payment',
            name='pension_apply',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True),
        ),
    ]
