# Generated by Django 2.1.3 on 2019-02-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffwelfare', '0004_auto_20190225_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True),
        ),
        migrations.AddField(
            model_name='staffsalary',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000000, null=True),
        ),
    ]
