# Generated by Django 2.1.3 on 2019-02-04 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasker',
        ),
        migrations.AddField(
            model_name='task',
            name='tasker',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
