# Generated by Django 2.1.3 on 2019-02-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190204_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tasker',
        ),
        migrations.AddField(
            model_name='task',
            name='tasker',
            field=models.CharField(default='djckvkddfdfdf', max_length=255),
            preserve_default=False,
        ),
    ]
